CUDA_VISIBLE_DEVICES=0 python run_src/ours/run_ours.py \
    --mode run \
    --method ours \
    --dataset_name GSM8K \
    --test_json_filename test_all \
    --mcts_reward_mode last_only \
    --enable_tot \
    --model_ckpt /path/to/model \
    --note default \
    --answer_selection_metric select_response \
    --answer_selection_mode topk \
    --topk 1 \
    --num_rollouts 16
